services:
  App\Crossword\Infrastructure\Adapter\Dictionary\DictionaryAdapter: ~
  App\Crossword\Infrastructure\Cache\RedisClient: ~

  Psr\Cache\CacheItemPoolInterface: '@App\Crossword\Infrastructure\Cache\RedisClient'
  App\Crossword\Domain\Port\DictionaryInterface: '@App\Crossword\Infrastructure\Adapter\Dictionary\DictionaryAdapter'