services:
  App\Crossword\Infrastructure\Provider\DictionaryProvider: ~
  App\Crossword\Infrastructure\Cache\RedisClient: ~

  Psr\Cache\CacheItemPoolInterface: '@App\Crossword\Infrastructure\Cache\RedisClient'
  App\Crossword\Domain\Service\Provider\DictionaryProviderInterface: '@App\Crossword\Infrastructure\Provider\DictionaryProvider'