services:
  App\Game\Infrastructure\Adapter\Crossword\CrosswordAdapter: ~

  App\Game\Domain\Repository\PersistPlayerRepositoryInterface: '@App\Game\Infrastructure\Repository\Doctrine\PersistPlayerRepository'
  App\Game\Domain\Repository\ReadPlayerRepositoryInterface: '@App\Game\Infrastructure\Repository\Doctrine\ReadPlayerRepository'
  App\Game\Domain\Service\PasswordEncoderInterface: '@App\Game\Infrastructure\Encoder\MD5Encoder'
  App\Game\Domain\Port\CrosswordInterface: '@App\Game\Infrastructure\Adapter\Crossword\CrosswordAdapter'