language: php

php:
  - '8.0'

services:
  - docker

cache: bundler

jobs:
  fast_finish: true

env:
  global:
    - DOCKER_COMPOSE=1.25.5

sudo: required

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
before_script:
  - docker-compose exec php sh -c "php -d memory_limit=-1 composer install -n"
script:
  - docker-compose -f docker-compose.test.yml run tests