language: php

php:
  - '8.0'

services:
  - docker

cache: bundler

jobs:
  fast_finish: true

env:
  global:
    - DOCKER_COMPOSE=1.25.5

sudo: required

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
script:
  - cd docker && docker-compose -f docker-compose.test.yml run tests
after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover code/tests/coverage.clover