#swager
swager.index:
    path: /swagger
    controller: App\Shared\UI\Web\SwaggerIndexAction
swager.update:
    path: /swagger/update
    controller: App\Shared\UI\Web\SwaggerUpdateAction
#dictionary
dictionary.api.words.word:
    path: /dictionary/words/{language}/word
    controller: App\Dictionary\UI\Rest\WordAction
dictionary.api.language:
    path: /dictionary/languages
    controller: App\Dictionary\UI\Rest\LanguagesAction