#swager
swager:
    path: /swagger
    controller: App\Dictionary\UI\Web\SwaggerIndexPageAction
swager.update:
    path: /swagger/update
    controller: App\Dictionary\UI\Web\SwaggerUpdateAction
#api
dictionary.api.words.word:
    path: /dictionary/words/{language}/word
    controller: App\Dictionary\UI\Rest\WordAction
dictionary.api.language:
    path: /dictionary/languages
    controller: App\Dictionary\UI\Rest\LanguagesAction