#swager
swager.index:
    path: /swagger
    controller: App\SharedKernel\UI\Web\SwaggerIndexAction
swager.update:
    path: /swagger/update
    controller: App\SharedKernel\UI\Web\SwaggerUpdateAction
#dictionary
dictionary.api.words.word:
    path: /api/dictionary/words/{language}
    controller: App\Dictionary\UI\Rest\WordAction
dictionary.api.languages:
    path: /api/dictionary/languages
    controller: App\Dictionary\UI\Rest\LanguagesAction
#crossword
crossword.api.build:
    path: /api/crossword/build/{language}/{type}/{level}
    controller: App\Crossword\UI\Rest\BuildAction
crossword.api.levels:
    path: /api/crossword/levels
    controller: App\Crossword\UI\Rest\LevelsAction
crossword.api.type:
    path: /api/crossword/types
    controller: App\Crossword\UI\Rest\TypesAction
crossword.api.languages:
    path: /api/crossword/languages
    controller: App\Crossword\UI\Rest\LanguagesAction
#game