imports:
    - { resource: ../src/Crossword/config/services.yaml }
    - { resource: ../src/Dictionary/config/services.yaml }
    - { resource: ../src/Game/config/services.yaml }
    - { resource: ../src/SharedKernel/config/services.yaml }
    - { resource: ../src/Swagger/config/services.yaml }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $redisHost: '%env(resolve:REDIS_HOST)%'
            $redisPort: '%env(resolve:REDIS_PORT)%'
            $elasticHosts: ['%env(resolve:ELASTIC_HOST_1)%']
            $dictionaryList: '%dictionary_storage%'
            $googleApiHost: '%env(resolve:GOOGLE_DICTIONARY_API)%'
            $wikipediaApiHost: '%env(resolve:WIKIPEDIA_DICTIONARY_API)%'
            $dictionaryApiHost: '%env(resolve:DICTIONARY_API)%'
            $crosswordApiHost: '%env(resolve:CROSSWORD_API)%'
    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude:
            - '../src/SharedKernel/config/'
            - '../src/SharedKernel/tests/'
            - '../src/Swagger/config/'
            - '../src/Swagger/tests/'
            - '../src/Game/config/'
            - '../src/Game/tests/'
            - '../src/Game/Domain/Model/'
            - '../src/Game/Domain/Dto/'
            - '../src/Game/Domain/Events/DomainEventsSubscriber.php'
            - '../src/Game/Infrastructure/Repository/DoctrineMigrations/'
            - '../src/Game/UI/Web/'
            - '../src/Crossword/UI/API/'
            - '../src/Crossword/config/'
            - '../src/Crossword/tests/'
            - '../src/Crossword/Domain/Model/'
            - '../src/Crossword/Domain/Dto/'
            - '../src/Dictionary/UI/API/'
            - '../src/Dictionary/config/'
            - '../src/Dictionary/tests/'
            - '../src/Dictionary/Domain/Model/'
            - '../src/Dictionary/Domain/Dto/'
            - '../src/Dictionary/Application/Service/WordsStoragePopulate.php'
            - '../src/Dictionary/Application/Service/WordsStorageUpload.php'
            - '../src/Kernel.php'