# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    DICTIONARY_WEB_DIR: '%kernel.project_dir%/src/Dictionary/UI/Rest'
    dictionary_storage:
        en: '%kernel.project_dir%/data/english.txt'
        ru: '%kernel.project_dir%/data/russian.txt'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude:
            - '../src/Game/Domain/Model/'
            - '../src/Crossword/Domain/Model/'
            - '../src/Dictionary/Domain/Model/'
            - '../src/Dictionary/Domain/Dto/'
            - '../src/Crossword/Domain/Dto/'
            - '../src/Kernel.php'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Dictionary\UI\Web\:
        resource: '../src/Dictionary/UI/Web'
        tags: ['controller.service_arguments']

    App\Dictionary\UI\Rest\:
        resource: '../src/Dictionary/UI/Rest'
        tags: ['controller.service_arguments']
    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    #  ---------------- Shared -------------------

    GuzzleHttp\Client: ~
    App\Shared\Infrastructure\HttpClient\GuzzleClient:
        - '@GuzzleHttp\Client'

    App\Shared\Infrastructure\HttpClient\ResponseDataExtractor: ~

    Psr\Http\Client\ClientInterface: '@App\Shared\Infrastructure\HttpClient\GuzzleClient'
    App\Shared\Domain\Service\ResponseDataExtractorInterface: '@App\Shared\Infrastructure\HttpClient\ResponseDataExtractor'
    #  ---------------- Dictionary ----------------

    App\Dictionary\Infrastructure\Elastic\ClientFactory:
        arguments:
            - ['%env(resolve:ELASTIC_HOST_1)%']

    App\Dictionary\UI\Console\WordsPopulateCommand:
        arguments:
            $dictionaryList: '%dictionary_storage%'

    App\Dictionary\Infrastructure\Gateway\WordDefinitionGoogleApiGateway:
        arguments:
            $host: '%env(resolve:GOOGLE_DICTIONARY_API)%'
        calls:
            - setNext: ['@App\Dictionary\Infrastructure\Gateway\WordDefinitionWikipediaApiGateway']

    App\Dictionary\Infrastructure\Gateway\WordDefinitionWikipediaApiGateway:
        arguments:
            $host: '%env(resolve:WIKIPEDIA_DICTIONARY_API)%'

    App\Dictionary\Infrastructure\FileReader\TextFileReader: ~
    App\Dictionary\Infrastructure\Elastic\WordsStorage: ~

    App\Dictionary\Domain\Service\WordDefinitionApiGatewayInterface: '@App\Dictionary\Infrastructure\Gateway\WordDefinitionGoogleApiGateway'
    App\Dictionary\Domain\Service\WordsStorageInterface: '@App\Dictionary\Infrastructure\Elastic\WordsStorage'
    App\Dictionary\Domain\Service\FileReaderInterface: '@App\Dictionary\Infrastructure\FileReader\TextFileReader'

    #  ---------------- Crossword ----------------

    #  ---------------- Game ---------------------

