paths:
  - ../Features/
exclude_files: ~
layers:
  - name: PopulateStorage
    collectors:
      - type: className
        regex: App\\Dictionary\\Features\\PopulateStorage\\.*
  - name: SupportedLanguages
    collectors:
      - type: className
        regex: App\\Dictionary\\Features\\SupportedLanguages\\.*

  - name: WordsFinder
    collectors:
      - type: className
        regex: App\\Dictionary\\Features\\WordsFinder\\.*

ruleset:
  PopulateStorage: ~
  SupportedLanguages: ~
  WordsFinder: ~