paths:
  - ../Features/
exclude_files: ~
layers:
  - name: PopulateStorage
    collectors:
      - type: className
        regex: App\\Dictionary\\Features\\PopulateStorage\\.*
  - name: Languages
    collectors:
      - type: className
        regex: App\\Dictionary\\Features\\Languages\\.*

  - name: WordsFinder
    collectors:
      - type: className
        regex: App\\Dictionary\\Features\\WordsFinder\\.*

ruleset:
  PopulateStorage: ~
  Languages: ~
  WordsFinder: ~