parameters:
  dictionary_storage:
    en: '%kernel.project_dir%/data/english.txt'
    ru: '%kernel.project_dir%/data/russian.txt'

services:
  App\Dictionary\Features\SupportedLanguages\LanguagesAction:
    tags: [ 'controller.service_arguments' ]

  App\Dictionary\Features\WordsFinder\WordAction:
    tags: [ 'controller.service_arguments' ]

  App\Dictionary\Features\WordsFinder\Request\WordRequest: ~
  App\Dictionary\Infrastructure\Gateway\Wikipedia\WordDefinitionWikipediaApiGateway: ~
  App\Dictionary\Infrastructure\HttpClient\ResponseDataExtractor: ~

  App\Dictionary\Infrastructure\Gateway\Google\WordDefinitionGoogleApiGateway:
    calls:
      - setNext: ['@App\Dictionary\Infrastructure\Gateway\Wikipedia\WordDefinitionWikipediaApiGateway']

  App\Dictionary\Features\PopulateStorage\Populate\WordsStoragePopulate:
    arguments:
      - '@App\Dictionary\Infrastructure\FileReader\TextFileReader'
      - '@command.bus'
      - '@monolog.logger'

  App\Dictionary\Features\PopulateStorage\Upload\WordsStorageUpload:
    arguments:
        - '@App\Dictionary\Infrastructure\FileReader\CsvFileReader'
        - '@command.bus'
        - '@monolog.logger'

  App\Dictionary\Infrastructure\FileReader\TextFileReader: ~
  App\Dictionary\Infrastructure\FileReader\CsvFileReader: ~
  App\Dictionary\Infrastructure\Repository\Elastic\WriteWordsStorage: ~
  App\Dictionary\Infrastructure\Repository\Elastic\ReadWordsStorage: ~

  App\Dictionary\Features\PopulateStorage\Populate\Port\WordDefinitionApiGatewayInterface: '@App\Dictionary\Infrastructure\Gateway\Google\WordDefinitionGoogleApiGateway'
  App\Dictionary\Features\SupportedLanguages\Storage\LanguageStorageInterface: '@App\Dictionary\Infrastructure\Repository\Elastic\ReadWordsStorage'
  App\Dictionary\Features\WordsFinder\Storage\ReadWordsStorageInterface: '@App\Dictionary\Infrastructure\Repository\Elastic\ReadWordsStorage'
  App\Dictionary\Features\PopulateStorage\SaveStorage\Storage\WriteWordsStorageInterface: '@App\Dictionary\Infrastructure\Repository\Elastic\WriteWordsStorage'
  App\Dictionary\Infrastructure\HttpClient\ResponseDataExtractorInterface: '@App\Dictionary\Infrastructure\HttpClient\ResponseDataExtractor'