paths:
  - ../Features/
exclude_files: ~
layers:
  - name: Constructor
    collectors:
      - type: bool
        must:
          - type: className
            regex: App\\Crossword\\Features\\Constructor\\.*
        must_not:
          - type: className
            regex: App\\Crossword\\Features\\Constructor\\Message\\GenerateCrosswordMessage

  - name: Generator
    collectors:
      - type: className
        regex: App\\Crossword\\Features\\Generator\\.*

  - name: Languages
    collectors:
      - type: className
        regex: App\\Crossword\\Features\\Languages\\.*

  - name: Receiver
    collectors:
      - type: className
        regex: App\\Crossword\\Features\\Receiver\\.*

  - name: Types
    collectors:
      - type: className
        regex: App\\Crossword\\Features\\Types\\.*

ruleset:
  Constructor: ~
  Generator: ~
  Languages: ~
  Receiver: ~
  Types: ~