services:
  App\Crossword\Features\Types\TypesAction:
    tags: [ 'controller.service_arguments' ]

  App\Crossword\Features\Languages\LanguagesAction:
    tags: [ 'controller.service_arguments' ]

  App\Crossword\Features\Receiver\ConstructAction:
    tags: [ 'controller.service_arguments' ]

  App\Crossword\Features\Generator\CrosswordGenerator:
    arguments:


  App\Crossword\Features\Receiver\Request\ConstructRequest: ~
  App\Crossword\Infrastructure\Adapter\Dictionary\ApiDictionaryAdapter: ~
  App\Crossword\Infrastructure\Adapter\Dictionary\DirectDictionaryAdapter: ~
  App\Crossword\Infrastructure\Cache\RedisClient: ~
  App\Crossword\Infrastructure\Repository\Redis\PersistCrosswordRepository: ~
  App\Crossword\Infrastructure\HttpClient\ResponseDataExtractor: ~

  Psr\Cache\CacheItemPoolInterface: '@App\Crossword\Infrastructure\Cache\RedisClient'
  App\Crossword\Features\Constructor\Dictionary\DictionarySearchInterface: '@App\Crossword\Infrastructure\Adapter\Dictionary\DirectDictionaryAdapter'
  App\Crossword\Features\Languages\Dictionary\DictionaryLanguagesInterface: '@App\Crossword\Infrastructure\Adapter\Dictionary\DirectDictionaryAdapter'
  App\Crossword\Features\Constructor\PersistCrosswordRepositoryInterface: '@App\Crossword\Infrastructure\Repository\Redis\PersistCrosswordRepository'
  App\Crossword\Infrastructure\HttpClient\ResponseDataExtractorInterface: '@App\Crossword\Infrastructure\HttpClient\ResponseDataExtractor'