paths:
  - ../Features/
exclude_files: ~
layers:
  - name: Answers
    collectors:
      - type: bool
        must:
          - type: className
            regex: App\\Game\\Features\\Answers\\.*
        must_not:
          - type: className
            regex: App\\Game\\Features\\Answers\\CrosswordPuzzleSolvedEvent

  - name: Authorization
    collectors:
      - type: className
        regex: App\\Game\\Features\\Authorization\\.*

  - name: GamePlay
    collectors:
      - type: className
        regex: App\\Game\\Features\\GamePlay\\.*

  - name: History
    collectors:
      - type: className
        regex: App\\Game\\Features\\History\\.*

  - name: Player
    collectors:
      - type: bool
        must:
          - type: className
            regex: App\\Game\\Features\\Player\\.*
        must_not:
          - type: className
            regex: App\\Game\\Features\\Player\\Level\\LevelUpEvent

  - name: Registration
    collectors:
      - type: className
        regex: App\\Game\\Features\\Registration\\.*

ruleset:
  Answers: ~
  Authorization: ~
  GamePlay: ~
  History: ~
  Player: ~
  Registration: ~