services:
  App\Game\UI\Web\:
    resource: '../UI/Web'
    tags: [ 'controller.service_arguments' ]

  App\Game\Domain\Events\DomainEventsSubscriber:
    arguments:
      [ '@command.bus' ]
    tags:
      - { name: 'doctrine.event_subscriber' }

  App\Game\UI\Web\NewGameAction:
    tags: [ 'controller.service_arguments' ]
    arguments:
      - '@App\Game\Application\Service\PlayerFromTokenExtractor'

  App\Game\Application\Service\PlayerFromTokenExtractor: ~
  App\Game\Domain\Service\PlayerTokenHack: ~
  App\Game\Application\Request\LoginRequest: ~
  App\Game\Application\Request\AnswersRequest: ~
  App\Game\Application\Service\Auth\PlayerLogin: ~
  App\Game\Infrastructure\Adapter\Crossword\ApiCrosswordAdapter: ~
  App\Game\Infrastructure\Adapter\Crossword\DirectCrosswordAdapter: ~
  App\Game\Infrastructure\HttpClient\ResponseDataExtractor: ~

  App\Game\Infrastructure\Dao\Doctrine\HistoryDao:
    arguments:
      - doctrine.dbal.default_connection

  App\Game\Domain\Dao\HistoryDaoInterface: '@App\Game\Infrastructure\Dao\Doctrine\HistoryDao'
  App\Game\Domain\Repository\PersistPlayerRepositoryInterface: '@App\Game\Infrastructure\Repository\Doctrine\PersistPlayerRepository'
  App\Game\Domain\Repository\ReadPlayerRepositoryInterface: '@App\Game\Infrastructure\Repository\Doctrine\ReadPlayerRepository'
  App\Game\Domain\Service\Encoder\PasswordEncoderInterface: '@App\Game\Infrastructure\Encoder\MD5Encoder'
  App\Game\Domain\Service\Encoder\LetterEncoderInterface: '@App\Game\Infrastructure\Encoder\Base64Encoder'
  App\Game\Domain\Port\CrosswordInterface: '@App\Game\Infrastructure\Adapter\Crossword\DirectCrosswordAdapter'
  App\Game\Domain\Service\ResponseDataExtractorInterface: '@App\Game\Infrastructure\HttpClient\ResponseDataExtractor'