framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        # failure_transport: failed

        transports:
#             messages: '%env(MESSENGER_TRANSPORT_DSN)%/messages'
#             events: '%env(MESSENGER_TRANSPORT_DSN)%/events'
             messages: 'sync://'
             events: 'sync://'
            # failed: 'doctrine://default?queue_name=failed'

        routing:
             'App\Dictionary\Features\PopulateStorage\Populate\Message\SearchWordDefinitionMessage': messages
             'App\Dictionary\Features\PopulateStorage\SaveStorage\Message\SaveToStorageMessage': messages
             'App\Crossword\Features\Constructor\Message\GenerateCrosswordMessage': messages
             'App\Game\Features\Player\Level\LevelUpEvent': events
