controllers_game:
    resource: ../../src/Game/UI
    type: annotation

controllers_crossword:
    resource: ../../src/Crossword/UI
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation
